name: Build InstallerX-Revived Magisk Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download InstallerX-Revived APK
        run: |
          mkdir -p system/priv-app/PackageInstaller
          # جلب أحدث ملف APK من مستودع wxxsfxyzm/InstallerX-Revived تلقائيًا
          LATEST_APK=$(curl -s https://api.github.com/repos/wxxsfxyzm/InstallerX-Revived/releases/latest | grep "browser_download_url" | grep -i "\.apk" | head -n 1 | cut -d '"' -f 4)
          curl -L -o system/priv-app/PackageInstaller/PackageInstaller.apk "$LATEST_APK"

      - name: Create Zip Module
        run: |
          zip -r InstallerX-Revived-Magisk-Module.zip . -x ".git*" ".github*" "README.md"

      - name: Upload Module Artifact
        uses: actions/upload-artifact@v4
        with:
          name: InstallerX-Revived-Magisk-Module
          path: InstallerX-Revived-Magisk-Module.zip
